In [4]:
import pandas as pd
import yfinance as yf

In [ ]:
portfolio = pd.read_csv(r"../data/portfolio.csv")
portfolio.head()

  symbol asset_class  quantity currency         strategy
0    SPY      Equity       100      USD      Core Equity
1    QQQ      Equity        50      USD           Growth
2    IWM      Equity        75      USD        Small Cap
3    TLT       Rates       150      USD      Rates Hedge
4    GLD   Commodity        80      USD  Inflation Hedge

In [38]:
port_tickers = list(portfolio.symbol)

df = yf.download(port_tickers, period='1mo',auto_adjust=True)
df.head()

[*********************100%***********************]  8 of 9 completed

Price           Close                                                 \
Ticker            EEM         GLD        HYG         IWM         QQQ
Date
2026-05-15  65.070000  417.290009  79.055328  277.600006  708.929993
2026-05-18  64.970001  418.429993  79.134926  275.970001  705.880005
2026-05-19  64.260002  411.500000  78.945892  273.000000  701.530029
2026-05-20  65.459999  417.399994  79.453293  279.869995  713.150024
2026-05-21  66.029999  416.989990  79.493095  282.489990  714.510010

Price                                                          High  ...  \
Ticker             SPY        TLT         USO        UUP        EEM  ...
Date                                                                 ...
2026-05-15  739.169983  83.332230  148.229996  27.770000  65.470001  ...
2026-05-18  738.650024  83.232613  149.289993  27.700001  65.760002  ...
2026-05-19  733.729980  82.694733  152.960007  27.790001  64.849998  ...
2026-05-20  741.250000  83.581253  144.270004  27.730000  65.559998  ...
2026-05-21  742.719971  83.890030  142.539993  27.730000  66.349998  ...

Price            Open    Volume                                         \
Ticker            UUP       EEM      GLD       HYG       IWM       QQQ
Date
2026-05-15  27.719999  34830900  9360400  54466000  35408000  51792700
2026-05-18  27.680000  37739800  5628300  38596100  27243300  49834500
2026-05-19  27.790001  37009400  5419400  42904700  30276900  46827500
2026-05-20  27.790001  32484700  6005000  58906300  31562000  36779200
2026-05-21  27.799999  28726400  4679900  37584600  31680500  36415400

Price
Ticker           SPY       TLT       USO      UUP
Date
2026-05-15  60410800  50796000   5588300  1851100
2026-05-18  47843900  26166200  10817300  2992100
2026-05-19  54255900  35346600   5514800  1914800
2026-05-20  45768000  44498000  11573800  2509300
2026-05-21  43332200  24887000  10203800  1832400

[5 rows x 45 columns]

In [30]:
df.to_csv(r'../data/port_ticker_history_1mo.csv')

In [44]:
adj_close_df = df['Close']
adj_close_df
adj_close_df.to_csv(r'../data/port_ticker_history_1mo_adj_close.csv')

In [45]:
adj_close_df

Ticker,EEM,GLD,HYG,IWM,QQQ,SPY,TLT,USO,UUP
Date,,,,,,,,,
2026-05-15,65.070000,417.290009,79.055328,277.600006,708.929993,739.169983,83.332230,148.229996,27.770000
2026-05-18,64.970001,418.429993,79.134926,275.970001,705.880005,738.650024,83.232613,149.289993,27.700001
2026-05-19,64.260002,411.500000,78.945892,273.000000,701.530029,733.729980,82.694733,152.960007,27.790001
2026-05-20,65.459999,417.399994,79.453293,279.869995,713.150024,741.250000,83.581253,144.270004,27.730000
2026-05-21,66.029999,416.989990,79.493095,282.489990,714.510010,742.719971,83.890030,142.539993,27.730000
2026-05-22,65.879997,413.820007,79.503044,285.119995,717.539978,745.640015,84.348228,140.919998,27.770000
2026-05-26,68.400002,414.000000,79.771667,290.510010,730.280029,750.590027,84.766579,137.000000,27.750000
2026-05-27,68.389999,408.489990,79.721916,290.369995,729.450012,750.460022,84.965805,131.029999,27.750000
2026-05-28,68.610001,412.769989,79.821411,292.029999,735.599976,754.599976,85.404076,130.779999,27.700001
2026-05-29,68.599998,417.119995,79.901001,290.429993,738.309998,756.479980,85.424004,129.089996,27.660000
2026-06-01,70.080002,411.260010,79.839996,288.980011,742.739990,758.539978,85.470001,135.500000,27.760000
2026-06-02,70.800003,411.950012,79.900002,291.660004,746.159973,759.570007,85.650002,137.270004,27.760000
2026-06-03,69.919998,407.869995,79.680000,287.670013,744.210022,754.239990,85.309998,140.860001,27.860001
2026-06-04,69.099998,411.269989,79.830002,292.010010,740.609985,757.090027,85.500000,136.740005,27.840000
2026-06-05,64.589996,396.239990,79.430000,281.649994,705.059998,737.549988,85.059998,133.020004,28.020000
2026-06-08,65.750000,397.269989,79.540001,284.109985,716.070007,739.219971,84.620003,135.149994,28.030001
2026-06-09,65.820000,390.779999,79.620003,285.019989,707.830017,737.049988,85.120003,131.300003,28.010000
2026-06-10,64.660004,374.579987,79.470001,282.049988,693.690002,725.429993,84.879997,134.300003,28.049999
2026-06-11,67.500000,386.320007,79.940002,290.410004,717.119995,737.760010,85.980003,128.830002,27.950001
2026-06-12,67.879997,386.540009,79.940002,292.950012,721.340027,741.750000,85.769997,125.430000,27.950001
2026-06-15,69.654999,396.450012,80.080002,295.010010,743.099976,754.849976,85.705002,119.959999,27.924999